os: linux
dist: bionic

language: ruby
rvm: 2.7.0

cache: bundler

addons:
  ssh_known_hosts: "$server_ip"
  apt:
    packages:
    - libcurl4-openssl-dev
    
script:
- JEKYLL_ENV=production bundle exec jekyll b

before_install:
  - openssl aes-256-cbc -K $encrypted_2f88525daf9f_key -iv $encrypted_2f88525daf9f_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
  
after_success:
  - scp -r "$SOURCE_PATH" "$server_user"@"$server_ip":"$BLOG_PATH"
