os: linux
dist: bionic

language: ruby
rvm: 2.7.0

cache: bundler

addons:
  ssh_known_hosts: $server_ip
  apt:
    packages:
      - libcurl4-openssl-dev # required to avoid SSL error (for htmlproofer)
  
script:
  - JEKYLL_ENV=production bundle exec jekyll b
